spring:
  datasource:
    url: "jdbc:h2:mem:testdb"
    driver-class-name: "org.h2.Driver"
    username: "sa"
    password: "password"
  h2:
    console:
      enabled: true
  mail:
    host: sandbox.smtp.mailtrap.io
    port: 587
    username: b120fdd042fcdd
    password: 3acaa4443e2d64
    properties:
      smtp:
        auth: true
        starttls:
          enable: true

mail.from: "no-reply@report.com"